name: CI

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    PEP8:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              clean: true
              path: repo

          - name: Install autopep8
            run: |
              sudo apt-get install -y python3-autopep8
          - name: Check PEP8
            run: |
              cd repo
              bash autoformat.sh
